### ISSUE TITLE
Retail ROMs page: cheat codes

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/wiki#21]
https://wiki.ds-homebrew.com/ds-index/retail-roms says that cheat codes "generally have types A through E," though this is not true, they have types 0 through F, (although it's not that simple anyways because of types D0, D1, D2, etc).
Also, it only describes the E type cheat.

Is there a specific reason for these? Or was it just never finished?

**Comment by Kaisaan** [comment]
It's just not finished, DeadskullzJr is currently working on a comprehensive document for how cheat codes work.

**Comment by Kaisaan** [comment]
[This commit](https://github.com/DS-Homebrew/wiki/commit/19068d91dad8f2be4545fec2a0031e04f60f1c5a) has updated the info as needed. Closing.
