### ISSUE TITLE
Video players page

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/wiki#36]
I think it would be great to add a page about video players to the Wiki, for the DS Index.
This page would cover [MPEG4Player](https://gbatemp.net/threads/mpeg4-player-for-ds-and-dsi.544095/), MoonShell, [RocketVideoPlayer](https://github.com/RocketRobz/RocketVideoPlayer), [Tuna-viDS](https://github.com/chishm/tuna-vids), and FastVideoDS when that comes out.
The page would compare the video players' capabilities and flaws, as well as explain how to convert videos for the video players.

I would very much like to write this page myself, but I am not experienced with how video formats work or the technical details of the players, I haven't gotten videos working on MoonShell, I'm not sure of the best way to write about ffmpeg installation and usage, and I don't know about instructions for operating systems other than Windows.

**Comment by lifehackerhansol** [comment]
I could probably make a moonshell doc at some point.

**Comment by HotPizzaYT** [comment]
I could write a Tuna-ViDS guide, but that is all there will be on it at the moment, since I have no experience in the other formats, (besides Moonshell).

**Comment by lifehackerhansol** [comment]
A tuna-viDS and/or DPG guide would likely be useful, because I don't see a point in promoting any other formats at the moment.

**Comment by spellboundtriangle** [comment]
> I don't see a point in promoting any other formats at the moment.

Why so?

**Comment by RocketRobz** [comment]
> > I don't see a point in promoting any other formats at the moment.
> 
> Why so?

MPEG4Player isn't really stable, as it doesn't support videos longer than 30 mins or so, as well as some other factors.
Rocket Video Player, while having support for long videos, the audio desyncs later on, has occasional lock-ups fixed by closing and re-opening the lid, and the guide for converting videos is tedious.
