### ISSUE TITLE
Glossary page(s)

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/wiki#39]
I think it would be beneficial for the projects covered here to have glossary pages, especially for nds-bootstrap.
These would cover settings and relevant topics/bugs/etc.

The DS Index pages sort of do this, but they don't cover everything and don't necessarily tell what it means for the end user.

**Comment by Kaisaan** [comment]
I created a glossary page for [nds-bootstrap](https://wiki.ds-homebrew.com/nds-bootstrap/glossary). It only has info on the per-game settings. I think this is a good start though and is enough to close the issue since there's now a format to follow.
