### ISSUE TITLE
GBARunner2 versions

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/wiki#40]
(Currently) there are many different versions of GBARunner2. Wifi_link, hicode, ARM7/9DLDI DS/DSi/3DS, one or two different forks, and so on (and some of these are overlapping of course). I think a solid page or FAQ entry on which version should be used for which purpose would be beneficial.

**Comment by Epicpkmn11** [comment]
The WikiTemp page does already have a section on this: https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List#The_Various_Builds_and_Branches_for_3DS_and_DSi

A FAQ here would probably be good too though.

**Comment by Kaisaan** [comment]
A page on the various builds of GBARunner2 [has been made](https://wiki.ds-homebrew.com/gbarunner2/builds). @zenseii created the page and said that they will make some changes, as well as add links. I think having a page made is good enough to close this issue.
